let transactions=[];
(async()=>{await guardPage();await loadSummary();await loadTransactions();})();
async function loadSummary(){try{const d=await apiFetch("/accounting/summary"),s=d.summary;document.getElementById("totalIncome").textContent=`$${Number(s.total_income).toFixed(2)}`;document.getElementById("totalExpense").textContent=`$${Number(s.total_expense).toFixed(2)}`;document.getElementById("totalProfit").textContent=`$${Number(s.total_profit).toFixed(2)}`;document.getElementById("totalDue").textContent=`$${Number(s.total_due).toFixed(2)}`;}catch(e){console.error(e);}}
async function loadTransactions(){try{const d=await apiFetch("/accounting/transactions");transactions=d.transactions||[];renderTransactions(transactions);}catch(e){console.error(e);}}
function renderTransactions(rows){const tb=document.getElementById("transactionTableBody");if(!rows.length){tb.innerHTML=`<tr><td colspan="7" class="empty-state">No transactions found.</td></tr>`;return;}tb.innerHTML=rows.map(t=>`<tr><td>${formatDate(t.transaction_date)}</td><td>${formatStatus(t.transaction_type)}</td><td>${escapeHTML(t.category)}</td><td>${escapeHTML(t.customer_name||"-")}</td><td>${escapeHTML(t.tracking_number||"-")}</td><td class="${t.transaction_type==="income"?"income":"expense"}">${t.transaction_type==="income"?"+":"-"} ${escapeHTML(t.currency||"USD")} ${Number(t.amount||0).toFixed(2)}</td><td><span class="status-badge status-${escapeHTML(t.payment_status)}">${formatStatus(t.payment_status)}</span></td></tr>`).join("");}
document.getElementById("transactionForm")?.addEventListener("submit",async e=>{e.preventDefault();try{await apiFetch("/accounting/transactions",{method:"POST",body:JSON.stringify({transaction_type:document.getElementById("transactionType").value,category:document.getElementById("transactionCategory").value,amount:document.getElementById("transactionAmount").value,payment_status:document.getElementById("paymentStatus").value,payment_method:document.getElementById("paymentMethod").value,description:document.getElementById("transactionDescription").value.trim(),transaction_date:document.getElementById("transactionDate").value,currency:"USD"})});e.target.reset();closeTransactionModal();await loadSummary();await loadTransactions();}catch(err){alert(err.message);}});
function closeTransactionModal(){document.getElementById("transactionModal").classList.remove("active");}
document.getElementById("addTransactionButton")?.addEventListener("click",()=>{document.getElementById("transactionDate").value=new Date().toISOString().split("T")[0];document.getElementById("transactionModal").classList.add("active");});
document.getElementById("closeTransactionModal")?.addEventListener("click",closeTransactionModal);document.getElementById("cancelTransactionButton")?.addEventListener("click",closeTransactionModal);
document.getElementById("transactionSearch")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();renderTransactions(transactions.filter(t=>[t.category,t.description,t.customer_name,t.tracking_number,t.transaction_type].filter(Boolean).join(" ").toLowerCase().includes(q)));});
