let customers=[],editingCustomerId=null;
(async()=>{await guardPage();await loadCustomers();})();
async function loadCustomers(){try{const d=await apiFetch("/customers?limit=200");customers=d.customers||[];renderCustomers(customers);}catch(e){console.error(e);}}
function renderCustomers(rows){
 const tbody=document.getElementById("customerTableBody");
 if(!rows.length){tbody.innerHTML=`<tr><td colspan="6" class="empty-state">No customers found.</td></tr>`;return;}
 tbody.innerHTML=rows.map(c=>`<tr><td><strong>${escapeHTML(c.name)}</strong><br><small>${escapeHTML(c.email||"")}</small></td><td>${escapeHTML(c.phone)}</td><td>${escapeHTML(c.company||"-")}</td><td>${escapeHTML([c.city,c.country].filter(Boolean).join(", ")||"-")}</td><td>${c.shipment_count||0}</td><td><button class="table-button" onclick="viewCustomer(${c.id})">View</button> <button class="table-button" onclick="editCustomer(${c.id})">Edit</button></td></tr>`).join("");
}
document.getElementById("addCustomerButton")?.addEventListener("click",()=>{editingCustomerId=null;document.getElementById("customerModalTitle").textContent="Add Customer";document.getElementById("customerForm").reset();document.getElementById("customerCountry").value="Bangladesh";document.getElementById("customerModal").classList.add("active");});
document.getElementById("customerForm")?.addEventListener("submit",async e=>{
 e.preventDefault();const value=id=>document.getElementById(id).value.trim();const payload={name:value("customerName"),phone:value("customerPhone"),email:value("customerEmail"),company:value("customerCompany"),city:value("customerCity"),country:value("customerCountry"),address:value("customerAddress")};
 const b=document.getElementById("saveCustomerButton");b.disabled=true;b.textContent="Saving...";
 try{await apiFetch(editingCustomerId?`/customers/${editingCustomerId}`:"/customers",{method:editingCustomerId?"PUT":"POST",body:JSON.stringify(payload)});document.getElementById("customerModal").classList.remove("active");await loadCustomers();}
 catch(err){alert(err.message);}finally{b.disabled=false;b.textContent="Save Customer";}
});
window.editCustomer=id=>{const c=customers.find(x=>x.id===id);if(!c)return;editingCustomerId=id;document.getElementById("customerModalTitle").textContent="Edit Customer";["Name","Phone","Email","Company","City","Country","Address"].forEach(x=>{const key=x.toLowerCase();document.getElementById("customer"+x).value=c[key]||"";});document.getElementById("customerModal").classList.add("active");};
window.viewCustomer=async id=>{try{const d=await apiFetch(`/customers/${id}`);document.getElementById("detailsCustomerName").textContent=d.customer.name;document.getElementById("customerDetails").innerHTML=`<div class="detail-grid">${Object.entries(d.customer).filter(([k])=>["name","phone","email","company","city","country","address"].includes(k)).map(([k,v])=>`<div><span>${formatStatus(k)}</span><strong>${escapeHTML(v||"-")}</strong></div>`).join("")}</div><h3 class="section-title">Shipment History</h3><div class="table-wrapper"><table><thead><tr><th>Tracking</th><th>Route</th><th>Service</th><th>Status</th></tr></thead><tbody>${d.shipments.map(s=>`<tr><td>${escapeHTML(s.tracking_number)}</td><td>${escapeHTML(s.origin_country)} → ${escapeHTML(s.destination_country)}</td><td>${escapeHTML(s.service_type||"-")}</td><td>${formatStatus(s.status)}</td></tr>`).join("")||`<tr><td colspan="4">No shipments.</td></tr>`}</tbody></table></div>`;document.getElementById("customerDetailsModal").classList.add("active");}catch(e){alert(e.message);}};
function closeCustomerModal(){document.getElementById("customerModal").classList.remove("active");}
document.getElementById("closeCustomerModal")?.addEventListener("click",closeCustomerModal);document.getElementById("cancelCustomerButton")?.addEventListener("click",closeCustomerModal);
document.getElementById("closeDetailsModal")?.addEventListener("click",()=>document.getElementById("customerDetailsModal").classList.remove("active"));
document.getElementById("customerSearch")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();renderCustomers(customers.filter(c=>[c.name,c.phone,c.email,c.company,c.city,c.country].filter(Boolean).join(" ").toLowerCase().includes(q)));});
