let users=[],editingUserId=null;
(async()=>{const u=await guardPage();if(u?.role!=="admin"){alert("Administrator permission required.");location.href="dashboard.html";return;}await loadUsers();})();
async function loadUsers(){try{const d=await apiFetch("/users");users=d.users||[];renderUsers(users);}catch(e){alert(e.message);}}
function renderUsers(rows){const tb=document.getElementById("userTableBody");tb.innerHTML=rows.length?rows.map(u=>`<tr><td><strong>${escapeHTML(u.name)}</strong></td><td>${escapeHTML(u.email)}</td><td>${formatStatus(u.role)}</td><td><span class="status-badge status-${u.status}">${formatStatus(u.status)}</span></td><td>${formatDateTime(u.last_login_at)}</td><td><button class="table-button" onclick="editUser(${u.id})">Edit</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty-state">No users found.</td></tr>`;}
document.getElementById("addUserButton").addEventListener("click",()=>openUser());
function openUser(u=null){editingUserId=u?.id||null;document.getElementById("userModalTitle").textContent=u?"Edit User":"Add User";document.getElementById("userName").value=u?.name||"";document.getElementById("userEmail").value=u?.email||"";document.getElementById("userPassword").value="";document.getElementById("userPassword").required=!u;document.getElementById("passwordHint").textContent=u?"(leave blank to keep)":"*";document.getElementById("userRole").value=u?.role||"staff";document.getElementById("userStatus").value=u?.status||"active";document.getElementById("userModal").classList.add("active");}
window.editUser=id=>openUser(users.find(u=>u.id===id));
function close(){document.getElementById("userModal").classList.remove("active");}
document.getElementById("closeUserModal").addEventListener("click",close);document.getElementById("cancelUser").addEventListener("click",close);
document.getElementById("userForm").addEventListener("submit",async e=>{e.preventDefault();const payload={name:document.getElementById("userName").value.trim(),email:document.getElementById("userEmail").value.trim(),password:document.getElementById("userPassword").value,role:document.getElementById("userRole").value,status:document.getElementById("userStatus").value};try{await apiFetch(editingUserId?`/users/${editingUserId}`:"/users",{method:editingUserId?"PUT":"POST",body:JSON.stringify(payload)});close();await loadUsers();}catch(err){alert(err.message);}});
document.getElementById("userSearch").addEventListener("input",e=>{const q=e.target.value.toLowerCase();renderUsers(users.filter(u=>[u.name,u.email,u.role,u.status].join(" ").toLowerCase().includes(q)));});
